---
services:
  github-runner:
    image: ${DOCKER_IMAGE:-actions-runner-docker}
    container_name: github-runner
    restart: unless-stopped
    env_file: [".env"]
    environment:
      GITHUB_URL: "${GITHUB_URL}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      Runner_Work_Dir: "/srv/actions-runner-docker/_work"
    volumes:
      - ./_work:/srv/actions-runner-docker/_work
      - /var/run/docker.sock:/var/run/docker.sock
